app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route::get('logueo', 'autenticacionController@index');
Route::group(['middleware' => 'auth'], function () {

Route::get('/', 'principalController@index');
Route::resource('roles', 'rolesController');
Route::get('niveles/ajxniveles', 'nivelesController@listado');
Route::resource('niveles', 'nivelesController');
Route::resource('planes', 'planesController');
Route::resource('jornadas', 'jornadasController');
Route::resource('puestos', 'puestosController');
Route::resource('secciones', 'seccionesController');
Route::resource('grados', 'gradosController');
Route::get('asignarniveles/obtenerajx', 'planesnivelesController@bscajx');
Route::resource('asignarniveles', 'planesnivelesController');
Route::resource('salones', 'salonesController');
Route::resource('areas/autocomplete', 'areasController@areas');
Route::resource('areas', 'areasController');
Route::get('personas/autocomplete', 'personasController@bscautomplete');
Route::get('verusuario/autocomplete', 'UsuariosRolesController@bscautomplete1');//control de busqueda de empleado por puesto cj
Route::get('personas/autocomplete/docente/', 'personasController@buscadocente');
Route::resource('personas', 'personasController');
Route::resource('carreras', 'carrerasController');
Route::resource('gradoniveles', 'gradosnivelesController');
Route::resource('pensum/pensumgrado', 'asignacionareasController@pensumGrado');
Route::resource('pensum/grados', 'asignacionareasController@grados');
Route::resource('pensum', 'asignacionareasController');
Route::resource('subopciones', 'subopcionesController');
Route::resource('permisosroles', 'permisosrolesController');
Route::resource('usuarios', 'usuariosController');
Route::resource('prueba', 'pruebaController');
Route::resource('asignaciondocente/grados', 'asignaciondocenteController@getGrados');
Route::resource('asignaciondocente', 'asignaciondocenteController');
Route::get('inscripcionestudiantes/constancia', 'inscripcionController@constancia');
Route::resource('inscripcionestudiantes', 'inscripcionController');
Route::resource('municipios', 'municipioController');
Route::resource('unidades', 'unidadesController');
Route::resource('docente', 'docenteController');
Route::resource('foros', 'forosController');
Route::resource('estudiantes', 'miscursosController');
Route::resource('respuestasforos', 'respuestasforosController');

//cambios hechos por jose florian
Route::resource('verestudiantes', 'EstudianteController');//cj
Route::resource('verusuario', 'UsuariosRolesController');//cj
Route::resource('verusuario', 'UsuariosRolesController');//cj

//Route::resource('actividades', 'ActividadesController');
Route::resource('Actividad', 'ActividadesController');//cj
Route::resource('misactividades',  'misActividadesController');//cj
Route::resource('respuestaactividades', 'RespondeActividadController');//cj
Route::resource('misrespuestasactividades', 'MisRespuestasActividadController');//cj


Route::get('report', 'PdfController@invoice');

Route::get('reportinscripcion', 'inscripcionController@reports');




//Route::get('constancia', 'reportesController@constancia_inscripcion');
//Route::get('pagos', 'reportesController@constancia_inscripcion');
});//fin del rout group
/*Route::get('/', function () {
    return view('welcome');
});*/

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Estudiantes.php
<?php

namespace education;

use Illuminate\Database\Eloquent\Model;

class Estudiantes extends Model
{
    protected $table = 'ESTUDIANTES';

     /*
      Metodo para obtener los datos de un alumno por su id
    */
    public static function findEstudiante($id)
    {
      return ESTUDIANTES::where('id_estudiante', $id)->first();
    }

}

app/Http/Controllers/EstudianteController.php
<?php

namespace education\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;

use education\Http\Requests;
use education\Http\Controllers\menuController;
use education\Estudiantes;
use \Validator;
use Session;
use education\User;
use Auth;

class EstudianteController extends Controller
{
     protected $menu;
    protected $users;
    public function __construct()
    {
      $m = new menuController();
      $this->menu = $m->index();
       $this->users->email=$request['c'];

        $items2 = $this->users->findUsuarioWhere();
    }
    /**
     * Display a listing of the resource.
     *   
     * @return \Illuminate\Http\Response
     */
	public function index()
    {
        $user = User::where('id', Auth::user()->id)->first();
        if ($user->can(['crear-inscripcion', 'ver-inscripcion'])) {
          $estudiantes = Estudiantes::All();

          return view('estudiantesinscritos.index', ['estudiantes'=>$estudiantes, 'items'=>$this->menu]);

          //$personas_roles=Personas::join('PUESTOS as p', 'PERSONAS.id_puesto', '=', 'p.id_puesto');
          //return view('personas.index', ['personas_roles'=>$personas_roles, 'items'=>$this->menu]);
        }
        return abort(403);
    }
      public function show($id)
    {
        //
       $user = User::where('id', Auth::user()->id)->first();
        if ($user->can('ver-inscripcion')) {
          $estudiante = ESTUDIANTES::findEstudiante($id);
          return view('estudiantesinscritos.minscripcion', ['items'=>$estudiante, 'items'=>$this->menu]);
        }
        return abort(403);
    }

}

resources/views/estudiante/index.blade.php
@extends('principal')

@section('titulo')
  <title>Mis Cursos Asignados</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Mis Cursos Asignados</h1>
        @include('mensajes.msg')
      </div>
      <div class="col-sm-12">
        <div class="table-responsive">
          <table class="table table-hover table-bordered">
            <thead>
              <tr>
                <th>
                  NO
                </th>
                <th>
                  CURSO
                </th>
                <th>
                  NIVEL
                </th>
                <th>
                  GRADO
                </th>
                <th>
                  CARRERA
                </th>
                <th>
                  SECCION
                </th>
                <th>
                  PLAN
                </th>
                <th>
                  JORNADA
                </th>
                <th>
                  ACCIONES
                </th>
              </tr>
            </thead>
            <tbody>
              @foreach($cursos as $key => $curso)
                <tr>
                  <td>
                    {{ $key+1 }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_area) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_nivel) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_grado) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_carrera) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_seccion) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_plan) }}
                  </td>
                  <td>
                    {{ mb_strtoupper($curso->nombre_jornada) }}
                  </td>
                  <td>
                  {{--   <select class="form-control" onchange="window.location.href=this.value">
                      <option value="">Seleccione...</option>
                      <option value="/docente/create?a={{$curso->id_asignacion_area}}&b={{ $curso->id_asignacion_docente }}">Zona</option>
                      <option value="/foros?a={{$curso->id_asignacion_area}}&b={{ $curso->id_asignacion_docente }}">Foros</option>
                      <option value="/foros?a={{$curso->id_asignacion_area}}&b={{ $curso->id_asignacion_docente }}">Actividades</option>
                    </select>
                    --}}

                    <!-- Single button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Seleccione... <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><a href="/docente/create?a={{$curso->id_asignacion_area}}&b={{ $curso->id_asignacion_docente }}">Notas</a></li>
                    <li><a href="/foros?a={{$curso->id_asignacion_area}}&b={{ $curso->id_asignacion_docente }}">Foros</a></li>
                    <li><a href="#">Tareas</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Reportes</a></li>
                  </ul>
                </div>

                    <!--{{-- {!!link_to_route('docente.create', $title = ' Zona', $parameters = ['a'=>$curso->id_asignacion_area,'b'=>$curso->id_asignacion_docente], $attributes = ['class'=>'btn btn-primary fa fa-edit'])!!}
                    --}}-->
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-sm-12 text-center">
        {{ $cursos->setPath('docente')->links() }}
      </div>
    </div>
  </div>
@endsection