app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route::get('logueo', 'autenticacionController@index');
Route::group(['middleware' => 'auth'], function () {

Route::get('/', 'principalController@index');
Route::resource('roles', 'rolesController');
Route::get('niveles/ajxniveles', 'nivelesController@listado');
Route::resource('niveles', 'nivelesController');
Route::resource('planes', 'planesController');
Route::resource('jornadas', 'jornadasController');
Route::resource('puestos', 'puestosController');
Route::resource('secciones', 'seccionesController');
Route::resource('grados', 'gradosController');
Route::get('asignarniveles/obtenerajx', 'planesnivelesController@bscajx');
Route::resource('asignarniveles', 'planesnivelesController');
Route::resource('salones', 'salonesController');
Route::resource('areas/autocomplete', 'areasController@areas');
Route::resource('areas', 'areasController');
Route::get('personas/autocomplete', 'personasController@bscautomplete');
Route::get('verusuario/autocomplete', 'UsuariosRolesController@bscautomplete1');//control de busqueda de empleado por puesto cj
Route::get('personas/autocomplete/docente/', 'personasController@buscadocente');
Route::resource('personas', 'personasController');
Route::resource('carreras', 'carrerasController');
Route::resource('gradoniveles', 'gradosnivelesController');
Route::resource('pensum/pensumgrado', 'asignacionareasController@pensumGrado');
Route::resource('pensum/grados', 'asignacionareasController@grados');
Route::resource('pensum', 'asignacionareasController');
Route::resource('subopciones', 'subopcionesController');
Route::resource('permisosroles', 'permisosrolesController');
Route::resource('usuarios', 'usuariosController');
Route::resource('prueba', 'pruebaController');
Route::resource('asignaciondocente/grados', 'asignaciondocenteController@getGrados');
Route::resource('asignaciondocente', 'asignaciondocenteController');
Route::get('inscripcionestudiantes/constancia', 'inscripcionController@constancia');
Route::resource('inscripcionestudiantes', 'inscripcionController');
Route::resource('municipios', 'municipioController');
Route::resource('unidades', 'unidadesController');
Route::resource('docente', 'docenteController');
Route::resource('foros', 'forosController');
Route::resource('estudiantes', 'miscursosController');
Route::resource('respuestasforos', 'respuestasforosController');

//cambios hechos por jose florian
Route::resource('verestudiantes', 'EstudianteController');//cj
Route::resource('verusuario', 'UsuariosRolesController');//cj
Route::resource('verusuario', 'UsuariosRolesController');//cj

//Route::resource('actividades', 'ActividadesController');
Route::resource('Actividad', 'ActividadesController');//cj
Route::resource('misactividades',  'misActividadesController');//cj
Route::resource('respuestaactividades', 'RespondeActividadController');//cj
Route::resource('misrespuestasactividades', 'MisRespuestasActividadController');//cj


Route::get('report', 'PdfController@invoice');

Route::get('reportinscripcion', 'inscripcionController@reports');




//Route::get('constancia', 'reportesController@constancia_inscripcion');
//Route::get('pagos', 'reportesController@constancia_inscripcion');
});//fin del rout group
/*Route::get('/', function () {
    return view('welcome');
});*/

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Unidades.php
<?php

namespace education;

use Illuminate\Database\Eloquent\Model;

class Unidades extends Model
{
    protected $table = 'UNIDADES';
    public $timestamps = false;
}

app/Http/Controllers/unidadesController.php
<?php

namespace education\Http\Controllers;

use Illuminate\Http\Request;

use education\Http\Requests;
use education\Http\Requests\unidadesRequest;
use education\Http\Controllers\menuController;
use education\Repositories\unidadesRepository;
use Session;
class unidadesController extends Controller
{

    protected $menu;
    protected $unidades;
    public function __construct(unidadesRepository $unidad)
    {
      $m = new menuController;
      $this->menu = $m->index();
      $this->unidades = $unidad;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $unidades = $this->unidades->getUnidades();
        return view('unidades.index', ['items'=>$this->menu, 'unidades'=>$unidades]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('unidades.nunidad', ['items'=>$this->menu]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(unidadesRequest $request)
    {
        //dd('Valido');
        $this->unidades->nombre = $request['nombre_unidad'];
        $this->unidades->fecha_inicio =  $request['fecha_inicio'];
        $this->unidades->fecha_final = $request['fecha_final'];

        $existe = $this->unidades->existUnidad();
        if ($existe == 0) {
          $this->unidades->setUnidad();
          $msg = 'Se ha registrado la nueva unidad exitosamente!!!';
        } else {
          $msg = 'No se pudo registrar la unidad, porque el nombre de unidad, ya esta registrado!!!';
        }
        Session::flash('mensaje',$msg);
        return redirect('/unidades');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->unidades->id = $id;
        $unidad = $this->unidades->getUnidadById();
        return view('unidades.eunidad', ['items'=>$this->menu, 'unidad'=>$unidad]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(unidadesRequest $request, $id)
    {
        //dd('valido');
        $this->unidades->nombre = $request['nombre_unidad'];
        $this->unidades->fecha_inicio = $request['fecha_inicio'];
        $this->unidades->fecha_final = $request['fecha_final'];
        $this->unidades->id = $id;
        $this->unidades->updateUnidad();
        Session::flash('mensaje', 'Se ha actualizado los datos de la unidad exitosamente!!!');
        return redirect('/unidades');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/unidades/eunidad.blade.php
@extends('principal')

@section('titulo')
  <title>Editar Unidad</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Editar Unidad</h1>
        <p>
          Nota: Todos los campos con (*) son obligatorios.
        </p>
      </div>
      <div class="col-sm-12">
        {!!Form::model($unidad,['route'=>['unidades.update', $unidad->id_unidad], 'method'=>'PUT', 'class'=>'form-horizontal', 'id'=>'unidades'])!!}
          @include('unidades.form.campos')
        {!!Form::close()!!}
      </div>
    </div>
  </div>
@endsection

resources/views/unidades/index.blade.php
@extends('principal')

@section('titulo')
  <title>Unidades</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Unidades</h1>
        @include('mensajes.msg')
      </div>
      <div class="col-sm-12">
        {!!link_to_route('unidades.create', $title = ' Nueva Unidad', $parameters = null, $attributes = ['class'=>'btn btn-primary fa fa-plus'])!!}
        <br>
        <br>
      </div>
      <div class="col-sm-12">
        @if(count($unidades) ==  0)
          <p class="text-info">
            No se han registrado unidades aun.
          </p>
        @else
          <div class="table-responsive">
            <table class="table table-hover table-bordered">
              <thead>
                <tr>
                  <th>
                    NO
                  </th>
                  <th>
                    NOMBRE
                  </th>
                  <th>
                    FECHA_INICIO
                  </th>
                  <th>
                    FECHA_FINAL
                  </th>
                  <th>
                    EDITAR
                  </th>
                </tr>
              </thead>
              <tbody>
                @foreach($unidades as $key => $unidad)
                  <tr>
                    <td>
                      {{ $key+1 }}
                    </td>
                    <td>
                      {{ ucwords($unidad->nombre_unidad) }}
                    </td>
                    <td>
                      {{ $unidad->fecha_inicio }}
                    </td>
                    <td>
                      {{ $unidad->fecha_final }}
                    </td>
                    <th>
                      {!!link_to_route('unidades.edit', $title = ' Editar', $parameters = $unidad->id_unidad, $attributes = ['class'=>'btn btn-primary fa fa-edit'])!!}
                    </th>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        @endif
      </div>
    </div>
  </div>
@endsection

resources/views/unidades/nunidad.blade.php
@extends('principal')

@section('titulo')
  <title>Nueva Unidad</title>
@endsection

@section('cuerpo')
  <div id="page-wrapper">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-center">Nueva Unidad</h1>
        <p>
          Nota: Todos los campos con (*) son obligatorios.
        </p>
      </div>
      <div class="col-sm-12">
        {!!Form::open(['route'=>'unidades.store', 'method'=>'POST', 'class'=>'form-horizontal', 'id'=>'unidades'])!!}
          @include('unidades.form.campos')
        {!!Form::close()!!}
      </div>
    </div>
  </div>
@endsection